### ISSUE TITLE
viewWillAppear / viewDidAppear

### ISSUE THREAD

**Issue by ajacquelin** [michaelhenry/FlipBoardNavigationController#5]
Hello,

viewWillAppear / viewDidAppear
These methodes  are not called when you pop the current viewcontroller:
    [self.flipboardNavigationController popViewController];

**Comment by michaelhenry** [comment]
this might solved the issue [7d1b1918b114381d47137fb70e48abb4428819b9](https://github.com/michaelhenry/FlipBoardNavigationController/commit/7d1b1918b114381d47137fb70e48abb4428819b9) Thanks :)
